/* config-keepassx.h. Generated by cmake from config-keepassx.h.cmake */

#ifndef KEEPASSX_CONFIG_KEEPASSX_H
#define KEEPASSX_CONFIG_KEEPASSX_H

#define KEEPASSX_VERSION "2.0.2"

#define KEEPASSX_SOURCE_DIR "${CMAKE_SOURCE_DIR}"
#define KEEPASSX_BINARY_DIR "${CMAKE_BINARY_DIR}"

#define KEEPASSX_PREFIX_DIR "${CMAKE_INSTALL_PREFIX}"
#define KEEPASSX_PLUGIN_DIR "${PLUGIN_INSTALL_DIR}"
#define KEEPASSX_DATA_DIR "${DATA_INSTALL_DIR}"

#if !defined(Q_OS_MAC) && !defined(Q_OS_WIN)
#define HAVE_PR_SET_DUMPABLE 1
#endif

//#define HAVE_RLIMIT_CORE 1
//#define HAVE_PT_DENY_ATTACH 1

#endif // KEEPASSX_CONFIG_KEEPASSX_H
